### ISSUE TITLE
"WORLD" blocks have turned black

### ISSUE THREAD

**Issue by Wuzzy2** [Der1248/Labyrinthus#2]
In Minetest 5.9.1, the "WORLD" blocks (where you select the world) have turned black.

Tested in Labyrinthus 2.15.1.

I am familiar with this type of bug. My guess is this is due to a missing or wrong `use_texture_alpha`. This field is now required for some node (look it up).

**Comment by Der1248** [comment]
I haven't updated Minetest to the latest version yet and am currently developing and testing only on 5.6.x. However, I will fix that soon.

**Comment by Der1248** [comment]
Should be fixed with Labyrinthus 2.16.0.
