### ISSUE TITLE
Countdown repeated in chat if there are multiple clocks

### ISSUE THREAD

**Issue by Wuzzy2** [Der1248/Labyrinthus#5]
If you put multiple 30 second countdown clocks in a level and activate one of them, the same countdown message is repeated multiple times in the chat. E.g. if you have 3 clocks, the message "25sec left" appears three times (instead of just once).

**Comment by Der1248** [comment]
I haven't noticed it so far, as there is only one timer in any level. I will fix it for the upcoming version 2.16.0.

**Comment by Der1248** [comment]
Should be fixed with Labyrinthus 2.16.0.
