### ISSUE TITLE
Coordinates shown when pushing cyan arrow block

### ISSUE THREAD

**Issue by Wuzzy2** [Der1248/Labyrinthus#6]
If you push the block with the cyan double-arrows, the chat shows 4 numbers which look like coordinates to me.

This looks unintentional for me, probably a debug message that wasn't removed, right?

Labyrinthus 2.15.1.

**Comment by Der1248** [comment]
Yes, those are coordinates and just debug messages that I forgot to remove. I will remove them for the upcoming version 2.16.0

**Comment by Der1248** [comment]
Should be fixed with Labyrinthus 2.16.0.
