### ISSUE TITLE
Thumbs.db in menu directory

### ISSUE THREAD

**Issue by Wuzzy2** [Der1248/Labyrinthus#7]
There's a Thumbs.db file in the menu directory. I don't think this file was meant to be in the Git repository (It's a special Windows file that is automatically generated for thumbnails, it can be safely deleted.).

**Comment by Der1248** [comment]
Will be removed in the upcoming version 2.16.0

**Comment by Der1248** [comment]
Has been removed with Labyrinthus 2.16.0.
